[2023-03-17T00:08:11.956+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: First_DAG.bash_task manual__2023-03-17T00:03:09.265189+00:00 [queued]>
[2023-03-17T00:08:11.967+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: First_DAG.bash_task manual__2023-03-17T00:03:09.265189+00:00 [queued]>
[2023-03-17T00:08:11.968+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-17T00:08:11.968+0000] {taskinstance.py:1280} INFO - Starting attempt 2 of 2
[2023-03-17T00:08:11.969+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-17T00:08:11.990+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): bash_task> on 2023-03-17 00:03:09.265189+00:00
[2023-03-17T00:08:11.996+0000] {standard_task_runner.py:55} INFO - Started process 17327 to run task
[2023-03-17T00:08:12.003+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'First_DAG', 'bash_task', 'manual__2023-03-17T00:03:09.265189+00:00', '--job-id', '42', '--raw', '--subdir', 'DAGS_FOLDER/first.py', '--cfg-path', '/tmp/tmpn1d584y3']
[2023-03-17T00:08:12.004+0000] {standard_task_runner.py:83} INFO - Job 42: Subtask bash_task
[2023-03-17T00:08:12.189+0000] {task_command.py:388} INFO - Running <TaskInstance: First_DAG.bash_task manual__2023-03-17T00:03:09.265189+00:00 [running]> on host e831dd1240d3
[2023-03-17T00:08:12.288+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=First_DAG
AIRFLOW_CTX_TASK_ID=bash_task
AIRFLOW_CTX_EXECUTION_DATE=2023-03-17T00:03:09.265189+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-17T00:03:09.265189+00:00
[2023-03-17T00:08:12.290+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-03-17T00:08:12.291+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', "echo'command executed from Bash Operator'"]
[2023-03-17T00:08:12.309+0000] {subprocess.py:86} INFO - Output:
[2023-03-17T00:08:12.311+0000] {subprocess.py:93} INFO - /bin/bash: line 1: echocommand executed from Bash Operator: command not found
[2023-03-17T00:08:12.312+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-03-17T00:08:12.327+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-03-17T00:08:12.332+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=First_DAG, task_id=bash_task, execution_date=20230317T000309, start_date=20230317T000811, end_date=20230317T000812
[2023-03-17T00:08:12.351+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 42 for task bash_task (Bash command failed. The command returned a non-zero exit code 127.; 17327)
[2023-03-17T00:08:12.374+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-03-17T00:08:12.394+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
