[2023-03-17T23:40:12.658+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: First_DAG.bash_task_move manual__2023-03-17T23:40:09.546162+00:00 [queued]>
[2023-03-17T23:40:12.675+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: First_DAG.bash_task_move manual__2023-03-17T23:40:09.546162+00:00 [queued]>
[2023-03-17T23:40:12.676+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-17T23:40:12.677+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2023-03-17T23:40:12.678+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-17T23:40:12.706+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): bash_task_move> on 2023-03-17 23:40:09.546162+00:00
[2023-03-17T23:40:12.713+0000] {standard_task_runner.py:55} INFO - Started process 2677 to run task
[2023-03-17T23:40:12.718+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'First_DAG', 'bash_task_move', 'manual__2023-03-17T23:40:09.546162+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/first.py', '--cfg-path', '/tmp/tmpt_l9f2ue']
[2023-03-17T23:40:12.720+0000] {standard_task_runner.py:83} INFO - Job 34: Subtask bash_task_move
[2023-03-17T23:40:12.825+0000] {task_command.py:388} INFO - Running <TaskInstance: First_DAG.bash_task_move manual__2023-03-17T23:40:09.546162+00:00 [running]> on host 12e59bc4b2cf
[2023-03-17T23:40:12.935+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=First_DAG
AIRFLOW_CTX_TASK_ID=bash_task_move
AIRFLOW_CTX_EXECUTION_DATE=2023-03-17T23:40:09.546162+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-17T23:40:09.546162+00:00
[2023-03-17T23:40:12.937+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-03-17T23:40:12.939+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'cp \\Users\\yucel\\Data_Center\\DATA_LAKE\\dataset_raw.txt  \\Users\\yucel\\Data_Center\\CLEAN_DATA']
[2023-03-17T23:40:12.952+0000] {subprocess.py:86} INFO - Output:
[2023-03-17T23:40:12.957+0000] {subprocess.py:93} INFO - cp: cannot stat 'UsersyucelData_CenterDATA_LAKEdataset_raw.txt': No such file or directory
[2023-03-17T23:40:12.958+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-03-17T23:40:12.976+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-03-17T23:40:12.982+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=First_DAG, task_id=bash_task_move, execution_date=20230317T234009, start_date=20230317T234012, end_date=20230317T234012
[2023-03-17T23:40:13.002+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 34 for task bash_task_move (Bash command failed. The command returned a non-zero exit code 1.; 2677)
[2023-03-17T23:40:13.051+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-03-17T23:40:13.112+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
